DIGITALOCEAN.md, MAKEFILE_OPS.md, Makefile, README.md, _scripts/Makefile.projects, _scripts/Makefile.projects-custom-build, _scripts/Makefile.projects-custom-build-custom-install, _scripts/Makefile.projects-custom-install, _scripts/Makefile.projects-external, _scripts/Makefile.projects-no-open, _scripts/Makefile.readme, _scripts/create, _scripts/d.rymcg.tech, _scripts/funcs.sh, _scripts/user/README.md, _scripts/user/d.rymcg.tech, _templates/README.md, _templates/bare/.env-dist, _templates/bare/.gitignore, _templates/bare/Makefile, _templates/bare/README.md, _templates/bare/docker-compose.yaml, _templates/bare/whoami/Dockerfile
This creates a new CLI script called `d.rymcg.tech` that lets you interact with any of the Makefiles, from any working directory, opening README web-pages, and for making skeleton project directories. This script includes BASH shell TAB completion support.
=> CLI script

_scripts/funcs.sh, _scripts/reconfigure_password
Fails after populating env with proper length password
=> parameterize password

_scripts/dev-sync
Fixes #37 by fixing the infinite loop to not quit.
=> dev-sync stability

nextcloud/docker-compose.yaml
=> changed restart to unless-stopped on 2 services

jitsi-meet/.env-dist, jitsi-meet/docker-compose.yaml
upgrade jitsi meet to the latest stable version, and introduce JITSI_WEB_VERSION variable so the user can update themselves.
=> upgrade jitsi meet

_scripts/Makefile.globals
the multiple levels of indirection were making this fail.
Fixes #108
=> Fix error in calculating DEFAULT_SAVE_CLEARTEXT_PASSWORDS_JSON

_scripts/reconfigure_oauth2, audiobookshelf/README.md, drawio/README.md, grocy/README.md, homepage/README.md, invidious/README.md, lemmy/README.md, photoprism/README.md, piwigo/README.md, whoami/README.md, wordpress/README.md
You corrected my wording in the TFA readme. I copied it to the readmes of all the apps that incorporate TFA, and to the makefile question.
=> corrected wording in readmes

.tools.lock.json, Makefile, _scripts/Makefile.globals, _scripts/Makefile.lifecycle
Upgrades to script-wizard 0.1.23
=> check script-wizard install for all project `make config`

.gitignore, xbs/.env-dist, xbs/Makefile, xbs/README.md, xbs/api/Dockerfile, xbs/api/settings-dist.json, xbs/api/settings.json, xbs/config/Dockerfile, xbs/config/setup.sh, xbs/config/template/settings.template.json, xbs/docker-compose.yaml
This doesn't work yet, when I query https://${XBS_TRAEFIK_HOST}/info I don't see the correct information including the message and location. Why doesn't the setttings.json get read?
=> Make xbs config template

README.md, _scripts/array_join, _scripts/array_to_json, _scripts/funcs.sh, _scripts/reconfigure_compose_profiles_select, nginx/.env-dist, nginx/Makefile, nginx/README.md, nginx/docker-compose.instance.yaml, nginx/docker-compose.yaml, nginx/nginx/Dockerfile, nginx/nginx/default.template.conf, nginx/nginx/php-fpm.template.conf, nginx/php-fpm/Dockerfile, nginx/php-fpm/default.php, nginx/php-fpm/php.ini, nginx/php-fpm/phpinfo.php, sftp/Makefile
This adds the nginx webserver configured for serving static files, and PHP-fpm for serving PHP scripts.
This adds the reconfigure_compose_profiles_select which uses script-wizard to select the compose profiles, enabling or disabling the optional containers.
=> Nginx + PHP-fpm

_scripts/Makefile.cd, _scripts/Makefile.lifecycle, _scripts/d.rymcg.tech
=> Create contextual install hint after make config

_scripts/Makefile.lifecycle
=> Fix `make destroy` and `make uninstall` when service=foo specified

wireguard/.env-dist, wireguard/Makefile, wireguard/README.md, wireguard/docker-compose.instance.yaml, wireguard/docker-compose.yaml, wireguard/vpn.sh, wireguard/wireguard/Dockerfile, wireguard/wireguard/ipv6.sh, wireguard/wireguard/public_peer_ports.sh
This adds IPv6 support to the wireguard config among other refactorings.
=> Wireguard IPv6

wireguard/README.md, wireguard/vpn.sh
This adds a systemd unit for the wireguard service, to start it on boot.
=> Wireguard systemd

wireguard/wireguard/public_peer_ports.sh
specify the incoming public interface for all DNAT rules.
=> Fix wireguard DNAT interface

_scripts/instance
=> Account for no existing instances for `make switch`

sftp/docker-compose.instance.yaml
=> Check for `SFTP_VOLUMES=`

homepage/.env-dist, homepage/Makefile, homepage/homepage_autoconfig.sh
=> Fix Homepage service port if using port other than :443

_scripts/Makefile.lifecycle
=> Fix the destroy messaging

_scripts/d.rymcg.tech
Adds automated way of creating the SSH config and Docker context on your workstation.
=> d.rymcg.tech cli commands: ssh, new-context, install-docker

_attic/gitea/Makefile
changed `ROOT_DIR=..` to `ROOT_DIR=../..`  now that Gitea is in `_attic`
=> updated ROOT_DIR in Makefile now that gitea is in _attic

homepage/homepage/package.json, homepage/homepage/pnpm-lock.yaml
https://github.com/advisories/GHSA-78xj-cgh5-2h22
=> Homepage: Fix CVE-2023-42282 - upgrade ip package

traefik/setup.sh
=> Make traefik adduser portable to Debian and Fedora.

_attic/tiddlywiki-nodejs/Makefile, _attic/tiddlywiki-nodejs/tiddlywiki-base/Dockerfile, _scripts/port_forward, audiobookshelf/docker-compose.yaml
Just a few minor fixes I found, and I also wanted `port_forward` to echo the ssh command that creates the tunnel
=> Misc fixes

nextcloud/.env-dist, nextcloud/Makefile, nextcloud/README.md, nextcloud/docker-compose.instance.yaml, nextcloud/docker-compose.yaml, nextcloud/nextcloud/Dockerfile
- added instance
- added auth
- added custom mountpoint option
- fixed commented-env-vars issue
- added `make config` options to choose and configure S3 or docker volume for primary storage
- removed erroneous duplicate `restart` in docker-compose.yaml
=> Updated Nextcloud

README.md, thirteenft/.env-dist, thirteenft/Makefile, thirteenft/README.md, thirteenft/docker-compose.instance.yaml, thirteenft/docker-compose.yaml
=> Added 13ft

README.md, tesseract/.env-dist, tesseract/Makefile, tesseract/README.md, tesseract/docker-compose.instance.yaml, tesseract/docker-compose.yaml
Tesseract is a front-end for Lemmy instances.
=> Add Tesseract

_scripts/Makefile.lifecycle, _scripts/d.rymcg.tech
=> Page status results with less -FSX

glances/.env-dist, glances/Makefile, glances/docker-compose.instance.yaml
I added the ability to bnd mount `/` on host so Glances could report on disk space available on the host. What do you think?
=> Add bind-mount host / to Glances

_scripts/reconfigure_ask
=> Fix reconfigure_ask not not allow blank unless ALLOW_BLANK=1

_scripts/d.rymcg.tech
=> Modify tmp-context PS1 to show the context.

_attic/gitea/docker-compose.yaml, _attic/mailu/docker-compose.yaml, _attic/transmission-wireguard/docker-compose.yaml, archivebox/docker-compose.yaml, doh-server/docker-compose.yaml, forgejo/docker-compose.yaml, lemmy/docker-compose.yaml, nginx/docker-compose.yaml, piwigo/docker-compose.yaml, plausible/docker-compose.yaml, traefik-forward-auth/docker-compose.yaml, vaultwarden/docker-compose.yaml, wordpress/docker-compose.yaml
=> Changes restart policies to unless-stopped.

_scripts/d.rymcg.tech
=> Adds tmp-context args

README.md, _scripts/Makefile.lifecycle, _scripts/d.rymcg.tech
=> Adds context aliases for d.rymcg.tech CLI.

_scripts/reconfigure_header_authorization, _scripts/reconfigure_oauth2
Fixes #306 
Fixes #309 
Fixes #308
=> Fix oauth2 bugs

sftp/Makefile, sftp/README.md, sftp/docker-compose.yaml
=> SFTP adds interactive SSH key authorization: d make sftp ssh-authorize-key

_scripts/d.rymcg.tech, _scripts/reconfigure_sshd
=> Adds reconfigure_sshd

_scripts/d.rymcg.tech, _scripts/ssh_expose
This script publishes d.rymcg.tech workstation ports to through a public sentry.
Implements #312
=> Adds ssh_expose script (`d ssh-expose`)

invidious/.env-dist, invidious/README.md, invidious/docker-compose.yaml
Fixes invidious docker image so it can support arm64.
=> Fix invidious docker image to support arm64

homepage/homepage/start.sh, homepage/homepage/webhook_reloader.js
=> Fix homepage auto-config

_scripts/Makefile.lifecycle
=> Fixes install hint to reflect the instance.

Makefile, README.md, _scripts/d.rymcg.tech, _scripts/funcs.sh, _scripts/select_docker_network_cidr, backup-volume/.env-dist, backup-volume/Makefile, backup-volume/docker-compose.instance.yaml, backup-volume/setup.sh, postfix-relay/.env-dist, postfix-relay/Makefile, postfix-relay/README.md, postfix-relay/docker-compose.instance.yaml, postfix-relay/docker-compose.yaml
This adds a forwarding-only mail transfer agent.
=> Postfix relay

_scripts/d.rymcg.tech
=> tmp-context : export DOCKER_CONTEXT

invidious/.env-dist, invidious/Makefile, invidious/README.md, invidious/docker-compose.yaml
=> Invidious: Bypass google's block

backup-volume/README.md
=> Add restore instructions

_scripts/ask_echo_blank, _scripts/choose, _scripts/funcs.sh, archivebox/.env-dist, archivebox/Makefile, archivebox/README.md, archivebox/config/Dockerfile, archivebox/docker-compose.yaml
Add Makefile targets to manage snapshot scheduling in Archivebox. This required minor updates/additions to some `_scripts/` files.
=> Archivebox changes

README.md
=> Add sentence to README explaining how to work around subshell bug #389.

homepage/.env-dist, homepage/Makefile, homepage/docker-compose.instance.yaml
=> Add extra volumes to Homepage container.

baikal/docker-compose.instance.yaml, baikal/docker-compose.yaml
=> Apply bug fixes.

README.md, commentario/.env-dist, commentario/Makefile, commentario/README.md, commentario/config/Dockerfile, commentario/config/setup.sh, commentario/config/template/secrets.yaml, commentario/docker-compose.instance.yaml, commentario/docker-compose.yaml, nginx/docker-compose.yaml, nginx/nginx/Dockerfile
=> Adds Commentario

jitsi-meet/Makefile
Resolves #410 - adds delete-user target for jitsi-meet.
=> Add delete-user target for jitsi-meet.

README.md, caddy/.env-dist, caddy/Makefile, caddy/README.md, caddy/caddy/Caddyfile.template, caddy/caddy/Dockerfile, caddy/caddy/docker-entrypoint.sh, caddy/caddy/index.html, caddy/docker-compose.instance.yaml, caddy/docker-compose.yaml
This adds the Caddy HTTP server and TLS certificate manager
=> Adds Caddy

jitsi-meet/.env-dist, jitsi-meet/Makefile, jitsi-meet/README.md, jitsi-meet/docker-compose.yaml
This is tested to fix #416 (but maybe it was never broken)
=> update jitsi meet

lemmy/.env-dist, lemmy/config/Dockerfile, lemmy/config/config.toml, lemmy/config/setup.sh, lemmy/docker-compose.yaml
Add configurations to pictrs service telling it to prune old content.
=> Add pictrs config to auto-prune.

nextcloud/.env-dist, nextcloud/Makefile
=> Fixed password resetting in Makefile

nextcloud/.env-dist, nextcloud/Makefile, nextcloud/docker-compose.instance.yaml, nextcloud/docker-compose.yaml
Add PHP configs to set max upload file size.
Add HSTS headers.
=> Nextcloud php configs

traefik/Dockerfile, traefik/docker-compose.yaml
=> Cache bust Traefik image build.

traefik/docker-compose.yaml
=> Add Docker restart rule

vaultwarden/.env-dist, vaultwarden/docker-compose.yaml
Added env var to customize max file size for Vaultwarden's send file functionality.
=> Add SEND_FILE_SIZE_LIMIT

searxng/config/settings.yml, searxng/docker-compose.instance.yaml
=> Searxng json

open-webui/docker-compose.yaml
=> Adds security options for openweb-ui and ollama.

_scripts/Makefile.lifecycle
=> Adds config-render target
