EnigmaCurry/d.rymcg.tech

_docker_vm/Makefile
_docker_vm/README.md
_docker_vm/boot.sh
_docker_vm/build_qemu_debian_image.sh
_docker_vm/preseed.cfg
_docker_vm/shutdown.sh

Debian bookworm is currently unstable, but it includes an updated Linux kernel (6.1), which is useful for sysbox.

Update _docker_vm to use Debian bookworm

---

gitea/README.md

Updated gitea docs to mention the need for TRAEFIK_SSH_ENTRYPOINT_ENABLED=true in Traefik.

Gitea docs

---

README.md

This sentence in README confused me re: `make switch` 
> If you want to enter the sub-shell without automatically running `make config`, you can run `make switch` rather than `make instance`.
So I updated it to
> If you want to enter the sub-shell without automatically running `make config`, you can run `make switch instance=foo` rather than `make instance`.
This fixes [issue #88](https://github.com/EnigmaCurry/d.rymcg.tech/issues/88).

clarify `make switch` in readme

---

traefik/Makefile

This branch enables using Docker via the unix socket /var/run/docker.sock instead of the default SSH context.
Fixes #72 
Things that are still broken:
* traefik `make open` needs SSH still
* traefik cannot use host networking on Docker Desktop.

Docker socket

---

homepage/.env-dist
homepage/homepage/Dockerfile

There are newer versions of Homepage (one potentially nice feature is tabs), and the image source changed from `ghcr.io/benphelps/homepage` to `ghcr.io/gethomepage/homepage`.

docker image source changed, also updated default version

---

_scripts/Makefile.docker-compose

As part of #28 we need to make a common `make shell` target supports instances and a configurable service name to shell into. This creates the `docker-compose-shell` make target.
For example:
```
.PHONY: shell
shell:
@make --no-print-directory docker-compose-shell SERVICE=qbittorrent COMMAND=/bin/bash
```
This needs to be copied and customized to every app (!)

Add common `make shell` target helper

---

_scripts/Makefile.docker-compose

Improve the logic of choosing between /bin/bash and /bin/sh.
Adds these arguments:
```
```

Improves `make shell` and adds additional arguments

---

_scripts/colorize
_scripts/d.rymcg.tech
_scripts/funcs.sh

Changed `d.rymcg.tech context` to display the current context in green so it stands out better.

colorize current context in `d.rymcg.tech context`

---

traefik/config/config-template/header-authorization.yml

We forgot to test Traefik without the header auth configured :/

Selectively apply header auth middleware only if it has been configured

---

_scripts/Makefile.help
_scripts/project_help

This puts all the global targets at the top and all the project specific targets below.

Refactor the project help menu to reorganize the output

---

_scripts/funcs.sh

Move the localhost/rsync image build outside of the `DISABLE_VOLUME_RSYNC_CHECKS` check.
This is needed to ensure the rsync image always exists

Fix dev-sync rsync image build

---

wireguard/wireguard/ipv6.sh

Makes the wireguard ipv6 script run idempotent

Wireguard: fix ipv6 script

---

prometheus/.env-dist
prometheus/Makefile
prometheus/docker-compose.instance.yaml
prometheus/docker-compose.yaml

I'm working on adding instance and mtls to Prometheus.
In my local .env, Prometheus was working in my VPN. The only things I changed are commited here, but now I get "Bad Gateway". I'm testing with Prometheus in my VPN but I don't have any sentry authentication in front of it.
There don't appear to be any errors in Prometheus' logs, but this is in Traefik's log:
```
traefik-1      | time="2024-06-06T01:04:43Z" level=error msg="sourceRange is empty, IPAllowLister not created" entryPointName=websecure routerName=prometheus-default-prometheus@docker
```
But I have `PROMETHEUS_METRICS_IP_SOURCERANGE="0.0.0.0/0"` in my .env and Traefik seems to see the IPAllowList value:

Prometheus: adding instance and mtls

---

ttrss/.env-dist
ttrss/Makefile
ttrss/docker-compose.instance.yaml

Added mTLS to TTRSS and it works fine if you use TTRSS from its web UI. But if you use a client app (e.g., the official [Tiny Tiny RSS for Android](https://gitlab.tt-rss.org/tt-rss/tt-rss-android), or third party Android apps like TTRSS-Reader, Tiny Tiny Feed, Geekttrss), the client app can't connect to the TTRSS Server.
TTRSS does [support SSL cert auth](https://tt-rss.org/wiki/SSL%20Certificate%20Authentication), but _if_ that's going to allow client apps to access the TTRSS server via mTLS, installation of TTRSS might need to be something like:
1. `d make step-ca cert` to create the cert you want your android app to use
2.  `d make ttrss config` would ask which cert in `step-ca/certs` you want to use
3. `d make ttrss install` would build container with `Dockerfile`:
1. copying the cert …

add mtls to ttrss

---

traefik-forward-auth/traefik-forward-auth/Dockerfile

TFA install failed on [this line](https://github.com/EnigmaCurry/d.rymcg.tech/blob/5f9e05363ea16738b85541cc952e7513f19d7d0a/traefik-forward-auth/traefik-forward-auth/Dockerfile#L9-L10) when `TRAEFIK_FORWARD_AUTH_STEP_CA_ENABLED=false`
I changed syntax.

updated syntax in dockerfile

---

homepage/docker-compose.instance.yaml

Removed TLS from reloader_router because webhook would fail if Homepage was installed behind mTLS, and the webhook is protected by a secret key anyway

Removed TLS from reloader_router

---

homepage/.env-dist
homepage/Makefile
homepage/README.md
homepage/docker-compose.instance.yaml

This is so that it can use separate TLS options for the webhooks.

Fix homepage webhooks TLS options by moving them to a separate domain

---

immich/Makefile
yourls/.env-dist
yourls/Makefile

Fixes #292 by removing the default username and password.
In #290 reconfigure_ask was fixed to not allow blanks, so the user is forced to enter a non-blank value.

Remove default username/password for YOURLS

---

_scripts/d.rymcg.tech
_scripts/routes
icecast/Makefile
traefik/Makefile

This adds a make target to list the the traefik routes.
Fixes #337 
```
$ d routes
Service                    Entrypoint  URL                                                                 Destination
--------------             ----------  ---                                                                 ----------
whoami-whoami-1            web         http://whoami.delorean-dev.nogn.rymcg.tech/                         -
mosquitto-mosquitto-1      mqtt        mqtt://mqtt.delorean-dev.nogn.rymcg.tech:8883/                      -
forgejo-forgejo-1          websecure   https://git.delorean-dev.forwarding.network/logout                  -
forgejo-forgejo-1          websecure   https://git.delorean-dev.forwarding.network/logout2                 -
forgejo-forgejo-1          websecure …
```

`d routes` (`d make traefik routes`)

---

traefik/.env-dist
traefik/config/traefik.yml
traefik/setup.sh

Fixes #349 
This adds a 6th item to the CUSTOM_ENTRYPOINTS tuple, so this is a breaking change and existing entrypoints will need to be manually added to add `:false` onto the end.

Traefik tls entrypoint

---

Makefile
README.md

[`moreutils` ](https://joeyh.name/code/moreutils/) is now a required dependency. It can be installed via any package manager with that same name.

update deps, add moreutils.

---

archivebox/.env-dist

Uncomment ARCHIVEBOX_API_GATEWAY_CONTEXT in `.env-dist` with enigmacurry's repo as default value (which is the default value in `docker-compose.yaml` anyway, and because the repo was just updated to work correctly), because while it was commented, if a user uncommented it to use their own repo, `make config` would prompt them to delete the env var because it's not in `.env-dist`.

Uncomment ARCHIVEBOX_API_GATEWAY_CONTEXT in `.env-dist` 

---

commentario/README.md
commentario/docker-compose.yaml

Might add the postfix-relay back later, but its not working right now so I'm removing it. Just put the direct SMTP config instead.

remove commentario postfix-relay

---

jitsi-meet/.env-dist
jitsi-meet/docker-compose.yaml

It's possible that we'll be removing jitsi from d.ry, but as longs as it's still here, I had this change from when we were last trying to make it work: variablize the service versions.

Variablize service versions

---

archivebox/Makefile
commentario/Makefile
coturn/Makefile
drawio/Makefile
github-actions-runner/Makefile
immich/Makefile
invidious/Makefile
lemmy/Makefile
minio/Makefile
mopidy/Makefile
nextcloud/Makefile
nginx/Makefile
open-webui/Makefile
peertube/Makefile
photoprism/Makefile
piwigo/Makefile
plausible/Makefile
prometheus/Makefile
qbittorrent-wireguard/Makefile
redmine/Makefile
searxng/Makefile
speedtest-tracker/Makefile
ttrss/Makefile
whoami/Makefile
wordpress/Makefile
xbs/Makefile
yourls/Makefile

For every service that has more than 1 container you might want to visit, I left the `make shell` menu but also added back the `make shell service=xxx` functionality.
Resolves #454

Update `make shell` to include previous functionality: `service=xxx`

---

open-webui/.env-dist
open-webui/docker-compose.yaml

Swagger is only available in openwebui's dev environment. Added env var to change environment.
Resolved #480

Add dev environment option for Swagger
